### PR TITLE
Don’t start Parallels Tools on xhyve

### PR DESCRIPTION
**Pull request by ailispaw**
The branch has been renamed from #1 .

### CODE REVIEW

**Comment by ailispaw** [comment]
@legal90 I'm still waiting for a response from Parallels. Any update?

**Comment by legal90** [comment]
@ailispaw Sorry, I don't have any updates on this yet :(

**Comment by ailispaw** [comment]
@legal90 Thank you so much for your reply. :)

**Comment by ailispaw** [comment]
@legal90 I have been working on https://github.com/ailispaw/docker-root.
So I can wait for the new docker/boot2docker for boot2docker-xhyve.

FYI: I would love to create ailispaw/docker-root for Parallels someday.
https://github.com/ailispaw/docker-root-packer

**Comment by ailispaw** [comment]
@legal90 Hi,
I don't know why, but now it's working with boot2docker v1.8.3 and xhyve.
Thanks.

**Comment by legal90** [comment]
Great!

**Comment by ailispaw** [comment]
@legal90 I saw your PR at https://github.com/boot2docker/boot2docker/pull/1074.
I'm wondering that would cause this issue again.

**Comment by legal90** [comment]
@ailispaw I've just verified it and it works fine.
I've build boot2docker.iso v1.8.3 with my fix from boot2docker#1074 and then I've used it to boot xhyve VM (from your https://github.com/ailispaw/boot2docker-xhyve). 
So, `sudo /usr/local/etc/init.d/prltoolsd start` doesn't cause a VM crash anymore.

**Comment by ailispaw** [comment]
@legal90 Thank you so much for your testing.
Are you going to release your custom build boot2docker v1.8.3 to https://atlas.hashicorp.com/parallels/boxes/boot2docker?

**Comment by legal90** [comment]
Yes, I'll manage to do this soon.

**Comment by ailispaw** [comment]
:+1:

**Comment by ailispaw** [comment]
I confirmed that as well with https://github.com/tianon/boot2docker-legacy/releases/tag/v1.9.0-rc1.
Thanks.

**Pull request closed without merging**
