### PR TITLE
Version update to 1.8.1

### PR DESCRIPTION
**Pull request by timfallmk**
Update to 1.8.1 in parallel with boot2docker/boot2docker

### CODE REVIEW

**Comment by ailispaw** [comment]
Hi @timfallmk,
Thank you so much for your PR.

But I'm forcing on https://github.com/ailispaw/docker-root-xhyve now.
And I've been waiting for a response from Parallels at https://github.com/ailispaw/boot2docker/pull/1.
So I won't build a custom version of boot2docker here.

**Comment by ailispaw** [comment]
And also I'm waiting for https://github.com/docker/boot2docker.
It seems good for xhyve.

**Comment by ailispaw** [comment]
@timfallmk 
Otherwise, if you don't mind building it on your side and upload it on your repo,
It would be my pleasure to point the download URL of boot2docker-xhyve to your repo.

**Comment by ailispaw** [comment]
Oh, you have already done that. :)

**Comment by timfallmk** [comment]
That's fine. I confirmed that the newest version of `boot2docker` already has the parallels tools disabled from the start.

As for DockerRoot, I do like Rancher, but Docker seems to be sticking with `boot2docker` (likely since they bought it) for platforms that don't support `libcontainer` directly.

If you want to somehow link people to my iso, that's also fine, but I think just pointing to upstream `boot2docker` should also before. Once `xhyve` has some more tooling available, none of these workarounds should be necessary.

**Comment by ailispaw** [comment]
Thank you.

> I think just pointing to upstream boot2docker should also before. 

What does this mean?

**Comment by timfallmk** [comment]
Sorry mistype. s/before/be fine.

**Comment by ailispaw** [comment]
Oh, I see. Thanks anyway.
I will point it to the new docker/boot2docker, once that is released.

**Pull request closed without merging**
