### PR TITLE
Don’t start Parallels Tools on xhyve

### PR DESCRIPTION
**Pull request by ailispaw**
Relating to https://github.com/ailispaw/boot2docker-xhyve/issues/6

### CODE REVIEW

**Comment by ailispaw** [comment]
I don't know how to check whether in Parallels or not and then just commented out for now.

**Comment by ailispaw** [comment]
Hi @legal90,

I'm playing with xhyve for a while, but I have a problem with the original boot2docker v1.7.1.
https://github.com/ailispaw/boot2docker-xhyve/issues/6
It could not only cause a problem on xhyve, but also on other hypervisors.
Could you advise me? How can I check whether a VM is in Parallels or not?

**Comment by ailispaw** [comment]
Oops.

**Comment by ailispaw** [comment]
Moved to #2

**Comment by legal90** [comment]
Hi, @ailispaw! Glad to meet you again :)

> It could not only cause a problem on xhyve, but also on other hypervisors.
> Could you advise me? How can I check whether a VM is in Parallels or not?

Hm, it looks weird... In fact `prltoolsd` daemon does some checks on the start, so it should exit silently on bare metal and all hypervisors except Parallels. I personally verified this behavior on VirtualBox.

What happens if you run `sudo /etc/rc.d/prltoolsd` in the VM xhyve manually? Has `/var/log/parallels.log` been created?

**Comment by ailispaw** [comment]
HI @legal90,
Thank you for the reply.

When I execute `sudo /etc/rc.d/prltoolsd`, immediately I got the same error message at https://github.com/ailispaw/boot2docker-xhyve/issues/6#issue-95300897 and it freezes.

**Comment by ailispaw** [comment]
You can try by yourself.
https://github.com/ailispaw/boot2docker-xhyve

**Comment by legal90** [comment]
@ailispaw Thanks. I've forwarded the problem to people in Parallels responsible on this. 
Will let you know about any updates.

**Comment by ailispaw** [comment]
@legal90 Thank you so much for your help. :)

**Comment by ailispaw** [comment]
@legal90 I'm still waiting for a response from Parallels. Any update?

**Pull request closed without merging**
